/**
   USE OF THIS SOFTWARE IS GOVERNED BY THE TERMS AND CONDITIONS
   OF THE LICENSE STATEMENT AND LIMITED WARRANTY FURNISHED WITH
   THE PRODUCT.
   <p/>
   IN PARTICULAR, YOU WILL INDEMNIFY AND HOLD B2N LTD., ITS
   RELATED COMPANIES AND ITS SUPPLIERS, HARMLESS FROM AND AGAINST ANY
   CLAIMS OR LIABILITIES ARISING OUT OF THE USE, REPRODUCTION, OR
   DISTRIBUTION OF YOUR PROGRAMS, INCLUDING ANY CLAIMS OR LIABILITIES
   ARISING OUT OF OR RESULTING FROM THE USE, MODIFICATION, OR
   DISTRIBUTION OF PROGRAMS OR FILES CREATED FROM, BASED ON, AND/OR
   DERIVED FROM THIS SOURCE CODE FILE.
*/

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// All pin defs here


#define MONITOR_PIN 13

#if defined(MODULE_IS_SERVER)

#define RF_CE_PIN 8
#define RF_CSN_PIN 53

#define SERVER_BUTTON_PIN 12

#endif

#if defined(MODULE_IS_CLIENT)

#define RF_CE_PIN 8
#define RF_CSN_PIN 10

#define CLIENT_AMPERMETER_PIN A0
#define CLIENT_VOLTMETER_PIN A1

#define CLIENT_VOLTMETER_SLAVE_PIN A4
#define CLIENT_AMPERMETER_SLAVE_PIN A5

#endif





