/**
   USE OF THIS SOFTWARE IS GOVERNED BY THE TERMS AND CONDITIONS
   OF THE LICENSE STATEMENT AND LIMITED WARRANTY FURNISHED WITH
   THE PRODUCT.
   <p/>
   IN PARTICULAR, YOU WILL INDEMNIFY AND HOLD B2N LTD., ITS
   RELATED COMPANIES AND ITS SUPPLIERS, HARMLESS FROM AND AGAINST ANY
   CLAIMS OR LIABILITIES ARISING OUT OF THE USE, REPRODUCTION, OR
   DISTRIBUTION OF YOUR PROGRAMS, INCLUDING ANY CLAIMS OR LIABILITIES
   ARISING OUT OF OR RESULTING FROM THE USE, MODIFICATION, OR
   DISTRIBUTION OF PROGRAMS OR FILES CREATED FROM, BASED ON, AND/OR
   DERIVED FROM THIS SOURCE CODE FILE.
*/

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Server sensors reading and calculation information

#if defined(MODULE_IS_CLIENT)

#define CLIENT_SENSORS_TIMEOUT  100
uint32_t CLIENT_SENSORS_LAST_EXECUTE;

float CLIENT_SENSORS_LAST_AMPS;
float CLIENT_SENSORS_LAST_VOLTS;
FLOAT_FLOAT CLIENT_SENSORS_LAST_AH;

inline void CLIENT_SENSORS_INIT()
{
  CLIENT_SENSORS_LAST_EXECUTE = 0;
  CLIENT_SENSORS_LAST_AMPS = MERIX_NOT_AVAILABLE;
  CLIENT_SENSORS_LAST_VOLTS = MERIX_NOT_AVAILABLE;
  CLIENT_SENSORS_LAST_AH = FLOAT_FLOAT(MERIX_NOT_AVAILABLE);

  CLIENT_SENSORS_LAST_EXECUTE = millis();

  LOG64_SET(F("CLIENT_SENSORS: INIT"));
  LOG64_NEW_LINE;
}

// if somethings is not available - please fill with MERIX_NOT_AVAILABLE
inline void CLIENT_SENSORS_GET(float & amps, float & volts, FLOAT_FLOAT & ah)
{
  amps = CLIENT_SENSORS_LAST_AMPS;
  volts = CLIENT_SENSORS_LAST_VOLTS;
  ah = CLIENT_SENSORS_LAST_AH;
  CLIENT_SENSORS_LAST_AH = FLOAT_FLOAT(0.0f);
}

inline uint32_t CLIENT_SENSORS_GET_TIME_INTERVAL(uint32_t now, uint32_t lastExecute)
{
  uint64_t lastExecute_ = lastExecute;
  uint64_t loopCounter_ = now;
  if (lastExecute_ > loopCounter_)
  {
    loopCounter_ += 0xFFFFFFFF;
  }

  return (uint32_t)(loopCounter_ - lastExecute_);

}

inline void CLIENT_SENSORS_()
{
  uint32_t now = millis();
  if (DO_EXECUTE(now, CLIENT_SENSORS_LAST_EXECUTE, CLIENT_SENSORS_TIMEOUT))
  {
    uint32_t delta = CLIENT_SENSORS_GET_TIME_INTERVAL(now, CLIENT_SENSORS_LAST_EXECUTE);

    CLIENT_SENSORS_LAST_EXECUTE = now;

    CLIENT_SENSORS_LAST_VOLTS = CLIENT_VOLTMETER_GET();
    CLIENT_SENSORS_LAST_AMPS = CLIENT_AMPERMETER_GET();
    if (CLIENT_SENSORS_LAST_AMPS >= MERIX_NOT_AVAILABLE)
    {
      if (CLIENT_SENSORS_LAST_AH.GET() <= MERIX_NOT_AVAILABLE)
      {
        CLIENT_SENSORS_LAST_AH = FLOAT_FLOAT(0.0f);
      }

      FLOAT_FLOAT to_add = FLOAT_FLOAT(CLIENT_SENSORS_LAST_AMPS);
      to_add.MUL((float)delta);
      to_add.DIV(FLOAT_FLOAT(float(1000.0f * 60.0f * 60.0f)));

      CLIENT_SENSORS_LAST_AH.ADD(to_add);

      //LOG64_SET(F("SENSOR: AMPS_LAST["));
      //LOG64_SET(CLIENT_SENSORS_LAST_AMPS);
      //LOG64_SET(F("] VOLTS_LAST["));
      //LOG64_SET(CLIENT_SENSORS_LAST_VOLTS);
      //LOG64_SET(F("] AH["));
      //LOG64_SET(String(CLIENT_SENSORS_LAST_AH.GET(),12));
      //LOG64_SET(String(CLIENT_SENSORS_LAST_AH.GET_LO(),12));
      //LOG64_SET(F("]"));
      //LOG64_NEW_LINE;

    }

  }
}
#endif

